site_id: RN+SI0001
supervisors:
  - ip: 127.0.0.1
    port: 12111

rsmp_versions:
  - 3.1.1
  - 3.1.2
  - 3.1.3
  - 3.1.4

watchdog_interval: 1
watchdog_timeout: 2
acknowledgement_timeout: 2
store_messages: false
command_response_timeout: 1
status_response_timeout: 1
status_update_timeout: 1
reconnect_interval: 1

log:
  active: true
  color: true
  timestamp: true
  id: false
  ip: false
  site_id: true
  level: false
  text: true
  direction: true
  json: false
  acknowledgements: true
  watchdogs: true

