site_id: RN+SI0001
supervisors:
  - ip: 127.0.0.1
    port: 12111

sxl: traffic_light_controller

rsmp_versions:
  - 3.1.1
  - 3.1.2
  - 3.1.3
  - 3.1.4

components:
  main:
    C1:

watchdog_interval: 1
watchdog_timeout: 2
acknowledgement_timeout: 1
command_response_timeout: 1
status_response_timeout: 1
status_update_timeout: 1
reconnect_interval: 0.1

log:
  active: true
  color: true
  timestamp: true
  id: true
  component: true
  ip: false
  site_id: true
  level: false
  text: true
  direction: true
  json: true
  acknowledgements: false
  watchdogs: false

