site_id: RN+RC0001
port: 12111
supervisor_ip: 127.0.0.1
rsmp_versions:
  - 3.1.4

watchdog_interval: 1
watchdog_timeout: 5
acknowledgement_timeout: 5
store_messages: false
command_response_timeout: 1
status_response_timeout: 1
status_update_timeout: 1

log:
  active: true
  color: true
  timestamp: false
  ip: false
  site_id: false
  level: false
  text: true
  direction: true
  json: true
  acknowledgements: true
  watchdogs: true

