# rsmp simulator
- site_id: AA+BBCCC=DDD
  sxl_versions:
    - 1.1
  main_component: AA+BBCCC=DDDEE001
  components:
    - AA+BBCCC=DDDEE001
    - AA+BBCCC=DDDEE002
    - AA+BBCCC=DDDEE003
    - AA+BBCCC=DDDEE004
    - AA+BBCCC=DDDEE005

# ruby rsmp site
- site_id: RN+SI0001
  sxl_versions:
    - 1.1
  main_component: AA+BBCCC=DDDEE001
  components:
    - AA+BBCCC=DDDEE001
    - AA+BBCCC=DDDEE002
    - AA+BBCCC=DDDEE003
    - AA+BBCCC=DDDEE004
    - AA+BBCCC=DDDEE005
- site_id: RN+SI0002
  sxl_versions:
    - 1.1
  main_component: AA+BBCCC=DDDEE001
  components:
    - AA+BBCCC=DDDEE001
    - AA+BBCCC=DDDEE002
    - AA+BBCCC=DDDEE003
    - AA+BBCCC=DDDEE004
    - AA+BBCCC=DDDEE005