port: 12111
guest:
  sxl: tlc
  timer_interval: 0.1
  watchdog_interval: 0.1
  watchdog_timeout: 0.2
  acknowledgement_timeout: 0.2
log:
  active: true
  color: true
  timestamp: true
  id: true
  component: true
  ip: false
  port: true
  site_id: true
  text: true
  direction: true
  level: false
  json: true
  acknowledgements: false
  watchdogs: false

