site_id: RN+RS0001
port: 12111
rsmp_versions:
  - 3.1.4

watchdog_interval: 1
watchdog_timeout: 5
acknowledgement_timeout: 5
store_messages: false
command_response_timeout: 1
status_response_timeout: 1
status_update_timeout: 1

log:
  active: true
  timestamp: true
  ip: false
  site_id: false
  text: true
  direction: true
  json: false
  acknowledgements: false
  watchdogs: false

