site_id: RN+SU0001
port: 12111
rsmp_versions:
  - 3.1.4

watchdog_interval: 1
watchdog_timeout: 2
acknowledgement_timeout: 2
store_messages: false
command_response_timeout: 1
status_response_timeout: 1
status_update_timeout: 1

sites:
  AA+BBCCC=DDD:    # rsmp simulator
    sxl: core
  RN+SI0001:       # ruby rsmp site

log:
  active: true
  color: true
  timestamp: true
  id: true
  component: true
  ip: false
  site_id: true
  text: true
  direction: true
  level: false
  json: true
  acknowledgements: true
  watchdogs: true

