port: 12111
rsmp_versions:
  - 3.1.1
  - 3.1.2
  - 3.1.3
  - 3.1.4
  - 3.1.5

sites:
  :any:
    sxl: tlc

watchdog_interval: 1
watchdog_timeout: 2
acknowledgement_timeout: 2
store_messages: false
command_response_timeout: 1
status_response_timeout: 1
status_update_timeout: 1

log:
  active: true
  color: true
  timestamp: true
  id: true
  component: true
  ip: false
  port: true
  site_id: true
  text: true
  direction: true
  level: false
  json: true
  acknowledgements: false
  watchdogs: false

