port: 12111
guest:
  sxl: tlc
  intervals:
    timer: 0.1
    watchdog: 0.1
  timeouts:
    watchdog: 0.2
    acknowledgement: 0.2
log:
  active: true
  color: true
  timestamp: true
  id: true
  component: true
  ip: false
  port: true
  site_id: 9
  component_id: 3
  text: true
  direction: false
  level: false
  debug: true
  json: true
  acknowledgements: false
  watchdogs: false
