site_id: RN+SI0001
supervisors:
  - ip: 127.0.0.1
    port: 12111
sxl: tlc
sxl_version: 1.0.15
components:
  main:
    TC:
      cycle_time: 6
  signal_group:
    A1:
    A2:
    B1:
    B2:
  detector_logic:
    DL1:
signal_plans:
  1:
    dynamic_bands:
      1: 0
      2: 5
    states:
      A1: '11NBBB'
      A2: '1NBBBB'
      B1: 'BBB11N'
      B2: 'BBB1NB'
  2:
    states:
      A1: '111NBB'
      A2: '11NBBB'
      B1: 'BBB11N'
      B2: 'BBB1NB'
intervals:
  timer: 0.1
  watchdog: 0.1
  reconnect: 0.1
timeouts:
  watchdog: 0.2
  acknowledgement: 0.2
security_codes:
  1: '1111'
  2: '2222'
log:
  ip: false
  site_id: 9
  component: 2
  level: false
  debug: true
  json: true
  acknowledgements: false
  watchdogs: false
