site_id: RN+SI0001
supervisors:
  - ip: 127.0.0.1
    port: 12111

rsmp_versions:
  - 3.1.1
  - 3.1.2
  - 3.1.3
  - 3.1.4

watchdog_interval: 0.1
watchdog_timeout: 2
acknowledgement_timeout: 2
store_messages: false
command_response_timeout: 1
status_response_timeout: 1
status_update_timeout: 1
reconnect_interval: 1.1

log:
  active: false
  color: :light_black
  timestamp: false
  id: true
  ip: false
  site_id: false
  level: false
  text: true
  direction: true
  json: true
  acknowledgements: true
  watchdogs: true

